theme: osuny
_merge: deep
params:
  plausible: thesufficiencylab.org
  summary:
    position: hero
  search:
    active: true
  breadcrumb:
    position: hero-start
    footer:
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logowhite.svg"   
  menu:
    primary:
      level_2:
        title:
          active: true
  posts:
    index:
      layout: grid
